[application]
name = "PostMen"
default_platform = "desktop"
out_dir = "dist"
asset_dir = "assets"

[web.app]
title = "PostMen - REST Client"

[web.watcher]
reload_html = true
watch_path = ["src", "assets"]

[desktop]
enable_default_menu = false

[bundle]
name = "PostMen"
identifier = "com.postmen.app"
icon = ["assets/icons/AppIcon.icns"]
