<script setup lang="ts">
import {
  IconHome,
  IconCube,
  IconLayoutGrid,
  IconLogin,
  IconStar,
  IconLock,
  IconArrowLeft,
  IconChevronDown,
  IconChevronRight,
  IconPlus,
  IconUpload,
  IconDownload,
  IconX,
  IconSearch,
  IconDotsVertical,
  IconDots,
  IconSettings,
  IconPalette,
  IconLayoutSidebarLeftCollapse,
  IconLayoutSidebarLeftExpand,
  IconLayoutRows,
  IconLayoutColumns,
  IconLayoutBottombarCollapse,
  IconDeviceDesktop,
  IconSun,
  IconMoon,
  IconCheck,
  IconMinus,
  IconSquare,
  IconArrowRight,
  IconFileText,
  IconWorld,
  IconInfoCircle,
  IconDeviceFloppy,
  IconCopy,
  IconTrash,
  IconFolder,
  IconCode,
  IconArrowBackUp,
  IconArrowForwardUp,
  IconSend,
  IconDatabase,
  IconPencil,
} from "@tabler/icons-vue";
const icons = {
  home: IconHome,
  cube: IconCube,
  workspace: IconLayoutGrid,
  openWorkspace: IconLogin,
  star: IconStar,
  lock: IconLock,
  back: IconArrowLeft,
  down: IconChevronDown,
  right: IconChevronRight,
  plus: IconPlus,
  upload: IconUpload,
  download: IconDownload,
  x: IconX,
  search: IconSearch,
  dotsVertical: IconDotsVertical,
  dots: IconDots,
  settings: IconSettings,
  palette: IconPalette,
  sidebar: IconLayoutSidebarLeftCollapse,
  sidebarExpand: IconLayoutSidebarLeftExpand,
  rows: IconLayoutRows,
  columns: IconLayoutColumns,
  collapse: IconLayoutBottombarCollapse,
  system: IconDeviceDesktop,
  light: IconSun,
  dark: IconMoon,
  check: IconCheck,
  minus: IconMinus,
  square: IconSquare,
  arrow: IconArrowRight,
  file: IconFileText,
  world: IconWorld,
  info: IconInfoCircle,
  save: IconDeviceFloppy,
  copy: IconCopy,
  trash: IconTrash,
  folder: IconFolder,
  code: IconCode,
  undo: IconArrowBackUp,
  redo: IconArrowForwardUp,
  send: IconSend,
  database: IconDatabase,
  pencil: IconPencil,
};
withDefaults(
  defineProps<{ name: keyof typeof icons; size?: number; stroke?: number }>(),
  { size: 16, stroke: 1.5 },
);
</script>

<template>
  <component
    :is="icons[name]"
    :size="size"
    :stroke="String(stroke)"
    aria-hidden="true"
    class="app-icon"
  />
</template>
