// Reproducible conservative inventory: installed npm production graph and
// macOS Cargo normal/build graph. Includes build tools; not a binary-size SBOM.
import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { readFile, readdir, mkdir, writeFile } from "node:fs/promises";
import { dirname, join, resolve, relative } from "node:path";
const hash = (bytes) => createHash("sha256").update(bytes).digest("hex");
// An explicit report destination keeps follow-up inventories separate from
// historical milestone evidence while refreshing the current bundled notices.
const reportPath = process.argv[2] ?? "docs/milestones/M4/dependency-notices.json";
const lock = JSON.parse(await readFile("package-lock.json", "utf8"));
const cargo = JSON.parse(
  execFileSync(
    "rtk",
    [
      "proxy",
      "cargo",
      "metadata",
      "--manifest-path",
      "src-tauri/Cargo.toml",
      "--locked",
      "--offline",
      "--format-version",
      "1",
      "--filter-platform",
      "aarch64-apple-darwin",
    ],
    { encoding: "utf8", maxBuffer: 32 * 1024 * 1024 },
  ),
);
const nodes = new Map(cargo.resolve.nodes.map((n) => [n.id, n])),
  reachable = new Set();
function visit(id) {
  if (reachable.has(id)) return;
  reachable.add(id);
  for (const d of nodes.get(id)?.deps ?? [])
    if (d.dep_kinds.some((k) => k.kind !== "dev")) visit(d.pkg);
}
visit(cargo.resolve.root);
const packages = [],
  texts = new Map();
let supplements = [];
try {
  supplements = JSON.parse(
    await readFile("docs/milestones/M4/notice-sources/sources.json", "utf8"),
  ).supplements;
} catch (error) {
  if (error.code !== "ENOENT") throw error;
}
async function collect(ecosystem, name, version, license, dir, explicit) {
  const files = (await readdir(dir, { withFileTypes: true }))
    .filter(
      (e) =>
        e.isFile() &&
        /^(licen[cs]e|copying|copyright|notice|ofl)([._-]|$)/i.test(e.name),
    )
    .map((e) => e.name);
  if (explicit && !files.includes(explicit)) files.push(explicit);
  const notices = [];
  for (const file of files.sort()) {
    const bytes = await readFile(join(dir, file));
    const sha256 = hash(bytes);
    texts.set(sha256, bytes.toString("utf8"));
    notices.push({ file, sha256 });
  }
  const supplement = supplements.find(
    (p) => p.name === name && p.version === version,
  );
  if (!notices.length && supplement)
    for (const source of supplement.sources) {
      const bytes = await readFile(source.file);
      if (hash(bytes) !== source.sha256)
        throw new Error(`Supplement hash mismatch: ${name}`);
      texts.set(source.sha256, bytes.toString("utf8"));
      notices.push(source);
    }
  packages.push({
    ecosystem,
    name,
    version,
    license: license ?? null,
    notices,
    ...(supplement ? { upstream: supplement } : {}),
    source:
      ecosystem === "cargo"
        ? `https://crates.io/api/v1/crates/${name}/${version}/download`
        : undefined,
  });
}
for (const [path, pkg] of Object.entries(lock.packages)) {
  if (!path.includes("node_modules/") || pkg.dev || pkg.link) continue;
  const dir = resolve(path),
    manifest = JSON.parse(await readFile(join(dir, "package.json"), "utf8"));
  await collect("npm", manifest.name, manifest.version, manifest.license, dir);
}
for (const pkg of cargo.packages.filter((p) => reachable.has(p.id) && p.source))
  await collect(
    "cargo",
    pkg.name,
    pkg.version,
    pkg.license,
    dirname(pkg.manifest_path),
    pkg.license_file,
  );
packages.sort(
  (a, b) =>
    a.ecosystem.localeCompare(b.ecosystem) ||
    a.name.localeCompare(b.name) ||
    a.version.localeCompare(b.version),
);
const missing = packages.filter((p) => !p.notices.length);
const report = {
  generatedAt: new Date().toISOString(),
  scope:
    "Conservative npm non-dev and macOS Cargo normal/build dependency graph; includes build-only/optional peer tools, does not assert all code is linked",
  npmLockSha256: hash(await readFile("package-lock.json")),
  cargoLockSha256: hash(await readFile("src-tauri/Cargo.lock")),
  packages,
  missing,
};
await mkdir(dirname(reportPath), { recursive: true });
await writeFile(
  reportPath,
  JSON.stringify(report, null, 2) + "\n",
);
let output =
  "PostMen dependency license texts\nGenerated by scripts/audit-notices.mjs from locally installed locked dependency sources.\nConservative inventory includes build-only tools. SPDX expressions below are upstream metadata, not a legal opinion.\nSee THIRD_PARTY_NOTICES.md for project assets and exceptions.\n\n";
for (const p of packages)
  output += `${p.ecosystem}: ${p.name}@${p.version}\nDeclared license: ${typeof p.license === "string" ? p.license : JSON.stringify(p.license)}\n${p.source ? `Unmodified upstream source: ${p.source}\n` : ""}${p.upstream ? `Upstream repository: ${p.upstream.repository}\nRevision: ${p.upstream.commit}\nAuthors (package metadata, not an invented copyright): ${p.upstream.authors.join(", ") || "Not supplied"}\n${p.upstream.review || "Pinned upstream license/copyright supplement"}\n` : ""}${p.notices.map((n) => `${n.file}: SHA256 ${n.sha256}${n.url ? ` (${n.url})` : ""}`).join("\n")}\n\n`;
for (const [sha256, text] of texts)
  output += `\n${"=".repeat(72)}\nSHA256 ${sha256}\n${"=".repeat(72)}\n${text}\n`;
if (missing.length === 0) await writeFile("licenses/DEPENDENCIES.txt", output);
console.log(
  JSON.stringify(
    {
      packages: packages.length,
      texts: texts.size,
      missing,
      artifact: missing.length
        ? null
        : relative(resolve("."), resolve("licenses/DEPENDENCIES.txt")),
    },
    null,
    2,
  ),
);
if (missing.length) process.exitCode = 1;
